package io.ddd4j.data.eventstore.jdbi;

import com.fasterxml.jackson.databind.json.JsonMapper;
import io.ddd4j.core.ddd.event.AggregateRootId;
import io.ddd4j.core.ddd.event.DomainEvent;
import io.ddd4j.core.ddd.event.EntityType;
import io.ddd4j.core.ddd.event.StringEntityId;
import io.ddd4j.core.ddd.event.StringEntityType;
import io.ddd4j.core.cqrs.eventstore.StoredEvent;
import io.ddd4j.core.cqrs.eventstore.jackson.EventPayloadSerializer;
import java.util.List;
import org.jdbi.v3.core.Jdbi;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

import static org.assertj.core.api.Assertions.assertThat;

/** PostgreSQL 容器轨：验证 JDBI 与 JPA 共享的 TEXT EventStore schema。 */
@Testcontainers(disabledWithoutDocker = true)
class JdbiEventStorePostgresIT {

    private static final String AGGREGATE_TYPE = "SampleAggregate";

    @Container
    static final PostgreSQLContainer POSTGRES = new PostgreSQLContainer("postgres:16-alpine");

    private static Jdbi jdbi;
    private static JdbiEventStore eventStore;

    @BeforeAll
    static void setUpStore() {
        jdbi = Jdbi.create(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
        jdbi.useHandle(handle -> handle.execute("""
                create table ddd4j_stored_event (
                    position bigint generated by default as identity primary key,
                    event_id varchar(36) not null,
                    aggregate_type varchar(128) not null,
                    aggregate_id varchar(128) not null,
                    version bigint not null,
                    event_type varchar(256) not null,
                    payload text not null,
                    correlation_id varchar(36),
                    causation_id varchar(36),
                    tenant_id varchar(64),
                    created_at timestamp with time zone not null,
                    constraint uk_aggregate_version unique (aggregate_type, aggregate_id, version)
                )"""));
        eventStore = new JdbiEventStore(jdbi,
                new EventPayloadSerializer(JsonMapper.builder().findAndAddModules().build()));
    }

    @BeforeEach
    void cleanStream() {
        jdbi.useHandle(handle -> handle.execute("delete from ddd4j_stored_event"));
    }

    @Test
    void appendAndReadShouldRoundTripTypedEventOnPostgres() {
        ItAggregateId aggregateId = new ItAggregateId("agg-pg-1");
        OccurredEvent first = new OccurredEvent("created");
        OccurredEvent second = new OccurredEvent("renamed");

        eventStore.append(AGGREGATE_TYPE, aggregateId, List.of(first, second), 0L);

        List<StoredEvent> stored = eventStore.read(AGGREGATE_TYPE, aggregateId);
        assertThat(stored).hasSize(2);
        assertThat(stored).extracting(StoredEvent::version).containsExactly(1L, 2L);
        assertThat(stored).allSatisfy(event -> {
            assertThat(event.aggregateId().asString()).isEqualTo("agg-pg-1");
            assertThat(event.payload()).isInstanceOf(OccurredEvent.class);
            assertThat(event.position()).isPositive();
        });
        assertThat(((OccurredEvent) stored.get(0).payload()).getFact()).isEqualTo("created");
        assertThat(eventStore.readAll(0L, 1)).hasSize(1);
    }

    static final class OccurredEvent extends DomainEvent<StringEntityId> {

        private String fact;

        OccurredEvent() {
            super("agg-pg-1");
        }

        OccurredEvent(String fact) {
            this();
            this.fact = fact;
        }

        public String getFact() {
            return fact;
        }

        public void setFact(String fact) {
            this.fact = fact;
        }
    }

    private record ItAggregateId(String value) implements AggregateRootId {

        private static final EntityType TYPE = new StringEntityType("SampleAggregate");

        @Override
        public EntityType getType() {
            return TYPE;
        }

        @Override
        public String asString() {
            return value;
        }

        @Override
        public String asTypedString() {
            return TYPE.asString() + ":" + value;
        }
    }
}
