package io.ddd4j.data.eventstore.jdbi;

import com.fasterxml.jackson.databind.json.JsonMapper;
import io.ddd4j.core.ddd.event.AggregateRootId;
import io.ddd4j.core.ddd.event.DomainEvent;
import io.ddd4j.core.ddd.event.EntityType;
import io.ddd4j.core.ddd.event.StringEntityId;
import io.ddd4j.core.ddd.event.StringEntityType;
import io.ddd4j.data.eventstore.AggregateVersionConflictException;
import io.ddd4j.data.eventstore.StoredEvent;
import io.ddd4j.data.eventstore.jackson.EventPayloadSerializer;
import org.h2.jdbcx.JdbcDataSource;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.statement.UnableToExecuteStatementException;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowableOfType;

/**
 * {@link JdbiEventStore} 纯 JDBI＋H2 全量契约集成测试（Task 5.3，本地必跑轨）。
 *
 * <p>零容器：{@code Jdbi.create(JdbcDataSource)} 直连 H2 内存库，DDL 在 {@code @BeforeAll}
 * 手工执行（表结构与 -jpa 模块 {@code StoredEventEntity} 同列集——含 {@code tenant_id} 列
 * 与 {@code uk_aggregate_version} 唯一约束，对齐阶段 5.1 评审 parity 发现）＋真实
 * {@code EventPayloadSerializer}（mapper 经 {@code findAndAddModules} 构建，零 mock）
 * ——完整验证 SPI 语义↔手写 SQL 的组装：追加/读回往返（真实 Jackson 序列化）、
 * 乐观锁冲突、全局 position 读流（SQL {@code limit} 真分页）、版本区间读、
 * 唯一约束的数据层兜底。
 *
 * <p>用例间隔离：每用例前清空表；{@code position} 为 IDENTITY 自增不重置，凡涉
 * position 的断言只做单调性与相对顺序，不做绝对值断言。
 *
 * @author <a href="https://github.com/partme-ai">PartMe.AI</a>
 * @since 2.0.x
 */
@DisplayName("JdbiEventStore 纯 JDBI + H2 全量契约 IT")
class JdbiEventStoreIT {

    private static final String AGGREGATE_TYPE = "SampleAggregate";

    /**
     * 与 -jpa 模块 StoredEventEntity 同构的 DDL（列集 parity：含 {@code tenant_id} 列、
     * {@code uk_aggregate_version} 唯一约束、TIMESTAMP WITH TIME ZONE 时间列）。
     */
    private static final String DDL = """
            create table if not exists ddd4j_stored_event (
                position bigint generated by default as identity primary key,
                event_id varchar(36) not null,
                aggregate_type varchar(128) not null,
                aggregate_id varchar(128) not null,
                version bigint not null,
                event_type varchar(256) not null,
                payload clob not null,
                correlation_id varchar(36),
                causation_id varchar(36),
                tenant_id varchar(64),
                created_at timestamp with time zone not null,
                constraint uk_aggregate_version unique (aggregate_type, aggregate_id, version)
            )""";

    private static Jdbi jdbi;

    private static JdbiEventStore eventStore;

    @BeforeAll
    static void setUpStore() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:ddd4j_event_store_jdbi_it;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        jdbi = Jdbi.create(dataSource);
        jdbi.useHandle(handle -> handle.execute(DDL));
        eventStore = new JdbiEventStore(jdbi,
                new EventPayloadSerializer(JsonMapper.builder().findAndAddModules().build()));
    }

    @BeforeEach
    void cleanStream() {
        jdbi.useHandle(handle -> handle.execute("delete from ddd4j_stored_event"));
    }

    @Test
    void appendThenRead_三事件追加_应全量读回且真实Jackson往返() {
        OccurredEvent first = new OccurredEvent("created");
        OccurredEvent second = new OccurredEvent("renamed");
        OccurredEvent third = new OccurredEvent("removed");
        ItAggregateId aggregateId = new ItAggregateId("agg-1");

        eventStore.append(AGGREGATE_TYPE, aggregateId, List.of(first, second, third), 0L);

        List<StoredEvent> stored = eventStore.read(AGGREGATE_TYPE, aggregateId);
        assertThat(stored).hasSize(3);
        assertThat(stored).extracting(StoredEvent::version).containsExactly(1L, 2L, 3L);
        // eventId／聚合定位经持久化往返保持
        assertThat(stored).extracting(event -> event.eventId().asString())
                .containsExactly(first.getEventId().asString(), second.getEventId().asString(),
                        third.getEventId().asString());
        assertThat(stored).extracting(StoredEvent::aggregateType).containsOnly(AGGREGATE_TYPE);
        assertThat(stored).allSatisfy(event -> {
            assertThat(event.aggregateId().asString()).isEqualTo("agg-1");
            // 真实 Jackson 往返：payload 反序列化为原事件类型且业务字段等值
            assertThat(event.payload()).isInstanceOf(OccurredEvent.class);
            assertThat(event.timestamp()).isNotNull();
            assertThat(event.position()).isPositive();
            // 无因果事件的 correlationId/causationId 为 null（EventId.valueOf 空安全路径）
            assertThat(event.correlationId()).isNull();
            assertThat(event.causationId()).isNull();
        });
        assertThat(((OccurredEvent) stored.get(0).payload()).getFact()).isEqualTo("created");
        assertThat(((OccurredEvent) stored.get(1).payload()).getFact()).isEqualTo("renamed");
        assertThat(((OccurredEvent) stored.get(2).payload()).getFact()).isEqualTo("removed");
    }

    @Test
    void append_乐观锁冲突_应抛异常且库中事件数不变() {
        ItAggregateId aggregateId = new ItAggregateId("agg-1");
        eventStore.append(AGGREGATE_TYPE, aggregateId,
                List.of(new OccurredEvent("created"), new OccurredEvent("renamed")), 0L);

        AggregateVersionConflictException exception = catchThrowableOfType(
                () -> eventStore.append(AGGREGATE_TYPE, aggregateId, List.of(new OccurredEvent("removed")), 0L),
                AggregateVersionConflictException.class);

        assertThat(exception).isNotNull();
        assertThat(exception.aggregateType()).isEqualTo(AGGREGATE_TYPE);
        assertThat(exception.aggregateId()).isEqualTo("agg-1");
        assertThat(exception.expectedVersion()).isZero();
        assertThat(exception.actualVersion()).isEqualTo(2L);
        // 冲突短路且事务回滚：库中仍只有已提交的 2 条，未留半截流
        assertThat(eventStore.read(AGGREGATE_TYPE, aggregateId)).hasSize(2);
    }

    @Test
    void readAll_跨聚合追加_应按全局position递增且SQL_limit真分页() {
        ItAggregateId firstAggregate = new ItAggregateId("agg-a");
        ItAggregateId secondAggregate = new ItAggregateId("agg-b");
        eventStore.append(AGGREGATE_TYPE, firstAggregate,
                List.of(new OccurredEvent("a1"), new OccurredEvent("a2")), 0L);
        eventStore.append(AGGREGATE_TYPE, secondAggregate,
                List.of(new OccurredEvent("b1"), new OccurredEvent("b2")), 0L);

        List<StoredEvent> all = eventStore.readAll(0L, 10);
        assertThat(all).hasSize(4);
        // 追加顺序即全局流顺序：跨聚合按 position 递增（含端点、无重复）
        assertThat(all).extracting(StoredEvent::position).isSorted().doesNotHaveDuplicates();
        assertThat(all).extracting(event -> event.aggregateId().asString())
                .containsExactly("agg-a", "agg-a", "agg-b", "agg-b");

        // SQL limit 真分页：limit=2 只取全局流前 2 条（StoredEvent 无 equals，按 position 比对）
        assertThat(eventStore.readAll(0L, 2)).extracting(StoredEvent::position)
                .containsExactly(all.get(0).position(), all.get(1).position());

        // fromPosition 含端点：从首条 position 起读为全量，越过后为尾部 3 条
        long firstPosition = all.get(0).position();
        assertThat(eventStore.readAll(firstPosition, 10)).hasSize(4);
        assertThat(eventStore.readAll(firstPosition + 1, 10)).extracting(StoredEvent::position)
                .containsExactly(all.get(1).position(), all.get(2).position(), all.get(3).position());
    }

    @Test
    void readByVersionRange_应返回闭区间内事件() {
        ItAggregateId aggregateId = new ItAggregateId("agg-1");
        eventStore.append(AGGREGATE_TYPE, aggregateId,
                List.of(new OccurredEvent("v1"), new OccurredEvent("v2"), new OccurredEvent("v3")), 0L);

        assertThat(eventStore.read(AGGREGATE_TYPE, aggregateId, 2L, 3L))
                .extracting(StoredEvent::version).containsExactly(2L, 3L);
        assertThat(eventStore.read(AGGREGATE_TYPE, aggregateId, 1L, 1L))
                .extracting(StoredEvent::version).containsExactly(1L);
        // 空区间（from > to / 流不存在）返回空列表，不报错
        assertThat(eventStore.read(AGGREGATE_TYPE, aggregateId, 4L, 9L)).isEmpty();
        assertThat(eventStore.read(AGGREGATE_TYPE, new ItAggregateId("agg-none"))).isEmpty();
    }

    /**
     * 数据层双保险：绕过 {@link JdbiEventStore} 的语义层乐观锁，同一表内直接插入
     * 两条同 {@code (aggregate_type, aggregate_id, version)} 行——
     * {@code uk_aggregate_version} 唯一约束应让第二条插入失败（ADR-0005 第二道防线）。
     */
    @Test
    void uk_aggregate_version约束_同流重复版本直插_应违反唯一约束() {
        jdbi.useHandle(handle -> insertRawRow(handle, "11111111-1111-1111-1111-111111111111", 1L));

        UnableToExecuteStatementException exception = catchThrowableOfType(
                () -> jdbi.useHandle(handle -> insertRawRow(handle,
                        "33333333-3333-3333-3333-333333333333", 1L)),
                UnableToExecuteStatementException.class);

        assertThat(exception).isNotNull();
        // 仅第一行落库（parity：tenant_id 列存在且默认为 NULL）
        assertThat(eventStore.readAll(0L, 10)).hasSize(1);
    }

    /**
     * 直插原始行（uk 约束用例绕过语义层，payload 无需合法 JSON；tenant_id 不写入，验证列可空）。
     */
    private void insertRawRow(org.jdbi.v3.core.Handle handle, String eventId, long version) {
        handle.createUpdate("""
                        insert into ddd4j_stored_event (event_id, aggregate_type, aggregate_id, version,
                        event_type, payload, created_at)
                        values (:eventId, :type, :id, :version, :eventType, :payload, :createdAt)""")
                .bind("eventId", eventId)
                .bind("type", AGGREGATE_TYPE)
                .bind("id", "agg-1")
                .bind("version", version)
                .bind("eventType", OccurredEvent.class.getName())
                .bind("payload", "{}")
                .bind("createdAt", java.time.ZonedDateTime.now())
                .execute();
    }

    /**
     * IT 样本事件：带一个业务字段的 payload 载体，验证真实 Jackson 往返等值。
     */
    static final class OccurredEvent extends DomainEvent<StringEntityId> {

        private String fact;

        OccurredEvent() {
            super("agg-1");
        }

        OccurredEvent(String fact) {
            this();
            this.fact = fact;
        }

        public String getFact() {
            return fact;
        }

        public void setFact(String fact) {
            this.fact = fact;
        }
    }

    /**
     * IT 自有字符串聚合根标识（受测类内部 StringAggregateRootId 为 private，无法引用；
     * 契约与 AggregateRootId 三方法一致）。
     */
    private record ItAggregateId(String value) implements AggregateRootId {

        private static final EntityType TYPE = new StringEntityType("SampleAggregate");

        @Override
        public EntityType getType() {
            return TYPE;
        }

        @Override
        public String asString() {
            return value;
        }

        @Override
        public String asTypedString() {
            return TYPE.asString() + ":" + value;
        }
    }
}
