<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <parent>
        <groupId>io.ddd4j</groupId>
        <artifactId>ddd4j-dependencies</artifactId>
        <version>${revision}</version>
        <relativePath>../ddd4j-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-data</artifactId>
    <packaging>pom</packaging>
    <name>${project.groupId}:${project.artifactId}</name>
    <description>ddd4j 数据抽象聚合：（mybatis / mybatis-plus / panache / jpa）+ crypto/external/logs/datascope 扩展。
    </description>
    <url>https://github.com/ddd-4-java/${project.artifactId}</url>

    <modules>
        <module>ddd4j-data-cqrs</module>
        <module>ddd4j-data-cqrs-dropwizard</module>
        <module>ddd4j-data-cqrs-helidon</module>
        <module>ddd4j-data-cqrs-javalin</module>
        <module>ddd4j-data-cqrs-micronaut</module>
        <module>ddd4j-data-cqrs-quarkus</module>
        <module>ddd4j-data-cqrs-spring</module>
        <module>ddd4j-data-cqrs-vertx</module>
        <module>ddd4j-data-crypto</module>
        <module>ddd4j-data-datascope</module>
        <module>ddd4j-data-event-store</module>
        <module>ddd4j-data-event-store-jpa</module>
        <module>ddd4j-data-event-store-panache</module>
        <module>ddd4j-data-event-store-jdbi</module>
        <module>ddd4j-data-event-store-r2dbc</module>
        <module>ddd4j-data-external</module>
        <module>ddd4j-data-jpa</module>
        <module>ddd4j-data-logs</module>
        <module>ddd4j-data-mybatis</module>
        <module>ddd4j-data-mybatisplus</module>
        <module>ddd4j-data-projection</module>
        <module>ddd4j-data-projection-jpa</module>
        <module>ddd4j-data-projection-jdbi</module>
        <module>ddd4j-data-projection-panache</module>
        <module>ddd4j-data-projection-r2dbc</module>
    </modules>

</project>
