<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j</groupId>
        <artifactId>ddd4j-extensions</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-web-webflux</artifactId>
    <description>Ddd4j WebFlux Component</description>

    <dependencies>
        <!-- For Ddd4j -->
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-extension-jackson</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- For Webjars -->
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>webjars-locator</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- For WebFlux -->
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-web</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>
    </dependencies>

</project>
