<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j</groupId>
        <artifactId>ddd4j</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-bom</artifactId>
    <packaging>pom</packaging>
    <description>Ddd4j Boot BOM (Bill of Materials) - 用于外部项目引用 ddd4j 模块版本管理</description>

    <dependencyManagement>
        <dependencies>
            <!-- Ddd4j Core -->
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <!-- Ddd4j Boot Components -->
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-extension-akka</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-cola</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-data-crypto</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-auth-datascope</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-extension-dubbo</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-excel</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-express</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-external</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-jackson</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-kafka</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-rabbit</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-mqtt</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-mqtt-mica</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-auth-license</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-logs</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-mybatis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-pf4j</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-satoken</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-validation</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-webflux</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.ddd4j</groupId>
                <artifactId>ddd4j-cmpt-webmvc</artifactId>
                <version>${revision}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
