<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.ddd4j</groupId>
        <artifactId>ddd4j-mq</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ddd4j-mq-pulsar</artifactId>
    <name>${project.groupId}:${project.artifactId}</name>
    <description>Ddd4j Apache Pulsar adapter based on pulsar-client 4.x and ddd4j MQ SPI. Pure Java, zero Spring.
    </description>
    <url>https://github.com/ddd-4-java/${project.artifactId}</url>

    <dependencies>
        <dependency>
            <groupId>io.ddd4j</groupId>
            <artifactId>ddd4j-mq-core</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- Pulsar 原生客户端（版本由 pulsar-bom 4.2.2 统一管理） -->
        <dependency>
            <groupId>org.apache.pulsar</groupId>
            <artifactId>pulsar-client</artifactId>
        </dependency>
    </dependencies>
</project>
