server:
  port: 8080

spring:
  application:
    name: ddd4j-sample-spring

# ddd4j 缓存配置
ddd4j:
  cache:
    order-stats:
      expired-seconds: 300
      maximum-size: 10000
    buyer-order-count:
      expired-seconds: 3600
      maximum-size: 10000
  mq:
    default-topic: DEFAULT
