package io.ddd4j.data.eventstore.r2dbc;

import com.fasterxml.jackson.databind.json.JsonMapper;
import io.ddd4j.core.ddd.event.AggregateRootId;
import io.ddd4j.core.ddd.event.DomainEvent;
import io.ddd4j.core.ddd.event.EntityType;
import io.ddd4j.core.ddd.event.StringEntityId;
import io.ddd4j.core.ddd.event.StringEntityType;
import io.ddd4j.data.eventstore.StoredEvent;
import io.ddd4j.data.eventstore.jackson.EventPayloadSerializer;
import io.r2dbc.postgresql.PostgresqlConnectionConfiguration;
import io.r2dbc.postgresql.PostgresqlConnectionFactory;
import java.util.List;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import static org.assertj.core.api.Assertions.assertThat;

/** PostgreSQL 容器轨：验证 R2DBC EventStore 与 JPA/JDBI 的 TEXT schema 互操作。 */
@Testcontainers(disabledWithoutDocker = true)
class R2dbcEventStorePostgresIT {

    private static final String AGGREGATE_TYPE = "SampleAggregate";

    @Container
    static final PostgreSQLContainer POSTGRES = new PostgreSQLContainer("postgres:16-alpine");

    private static PostgresqlConnectionFactory connectionFactory;
    private static R2dbcEventStore eventStore;

    @BeforeAll
    static void setUpStore() {
        connectionFactory = new PostgresqlConnectionFactory(PostgresqlConnectionConfiguration.builder()
                .host(POSTGRES.getHost())
                .port(POSTGRES.getMappedPort(5432))
                .database(POSTGRES.getDatabaseName())
                .username(POSTGRES.getUsername())
                .password(POSTGRES.getPassword())
                .build());
        eventStore = new R2dbcEventStore(connectionFactory,
                new EventPayloadSerializer(JsonMapper.builder().findAndAddModules().build()));
        execute("""
                create table ddd4j_stored_event (
                    position bigint generated by default as identity primary key,
                    event_id varchar(36) not null,
                    aggregate_type varchar(128) not null,
                    aggregate_id varchar(128) not null,
                    version bigint not null,
                    event_type varchar(256) not null,
                    payload text not null,
                    correlation_id varchar(36),
                    causation_id varchar(36),
                    tenant_id varchar(64),
                    created_at timestamp with time zone not null,
                    constraint uk_aggregate_version unique (aggregate_type, aggregate_id, version)
                )""").block();
    }

    @BeforeEach
    void cleanStream() {
        execute("delete from ddd4j_stored_event").block();
    }

    @Test
    void appendAndReadShouldRoundTripTypedEventOnPostgres() {
        ItAggregateId aggregateId = new ItAggregateId("agg-pg-1");
        OccurredEvent first = new OccurredEvent("created");
        OccurredEvent second = new OccurredEvent("renamed");

        StepVerifier.create(eventStore.append(AGGREGATE_TYPE, aggregateId, Flux.just(first, second), 0L))
                .verifyComplete();

        StepVerifier.create(eventStore.read(AGGREGATE_TYPE, aggregateId).collectList())
                .assertNext(stored -> {
                    assertThat(stored).hasSize(2);
                    assertThat(stored).extracting(StoredEvent::version).containsExactly(1L, 2L);
                    assertThat(stored).allSatisfy(event -> {
                        assertThat(event.aggregateId().asString()).isEqualTo("agg-pg-1");
                        assertThat(event.payload()).isInstanceOf(OccurredEvent.class);
                        assertThat(event.position()).isPositive();
                    });
                })
                .verifyComplete();
        StepVerifier.create(eventStore.readAll(0L, 1).count())
                .expectNext(1L)
                .verifyComplete();
    }

    private static Mono<Void> execute(String sql) {
        return Mono.usingWhen(
                connectionFactory.create(),
                connection -> Mono.from(connection.createStatement(sql).execute())
                        .flatMap(result -> Mono.from(result.getRowsUpdated()))
                        .then(),
                connection -> Mono.from(connection.close()),
                (connection, error) -> Mono.from(connection.close()),
                connection -> Mono.from(connection.close()));
    }

    static final class OccurredEvent extends DomainEvent<StringEntityId> {

        private String fact;

        OccurredEvent() {
            super("agg-pg-1");
        }

        OccurredEvent(String fact) {
            this();
            this.fact = fact;
        }

        public String getFact() {
            return fact;
        }

        public void setFact(String fact) {
            this.fact = fact;
        }
    }

    private record ItAggregateId(String value) implements AggregateRootId {

        private static final EntityType TYPE = new StringEntityType("SampleAggregate");

        @Override
        public EntityType getType() {
            return TYPE;
        }

        @Override
        public String asString() {
            return value;
        }

        @Override
        public String asTypedString() {
            return TYPE.asString() + ":" + value;
        }
    }
}
