package io.ddd4j.data.eventstore.r2dbc;

import com.fasterxml.jackson.databind.json.JsonMapper;
import io.ddd4j.core.ddd.event.AggregateRootId;
import io.ddd4j.core.ddd.event.DomainEvent;
import io.ddd4j.core.ddd.event.EntityType;
import io.ddd4j.core.ddd.event.StringEntityId;
import io.ddd4j.core.ddd.event.StringEntityType;
import io.ddd4j.data.eventstore.AggregateVersionConflictException;
import io.ddd4j.data.eventstore.StoredEvent;
import io.ddd4j.data.eventstore.jackson.EventPayloadSerializer;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.ConnectionFactories;
import io.r2dbc.spi.R2dbcException;
import io.r2dbc.spi.Statement;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.function.UnaryOperator;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@link R2dbcEventStore} 纯 r2dbc-h2＋H2 全量契约集成测试（Task 5.4，本地必跑轨）。
 *
 * <p>零容器：{@code ConnectionFactories.get("r2dbc:h2:mem:///esit;DB_CLOSE_DELAY=-1")}
 * 直连 H2 内存库，DDL 在 {@code @BeforeAll} 手工执行（表结构与 -jpa/-jdbi 模块同列集
 * ——含 {@code tenant_id} 列与 {@code uk_aggregate_version} 唯一约束，对齐阶段 5.1
 * 评审 parity 发现）＋真实 {@code EventPayloadSerializer}（mapper 经
 * {@code findAndAddModules} 构建，零 mock）——完整验证 AsyncEventStore 语义↔纯
 * {@code io.r2dbc.spi} Connection 原语的组装：追加/读回往返（真实 Jackson 序列化）、
 * 响应式事务的乐观锁冲突回滚、全局 position 读流（SQL {@code limit} 真分页）、
 * 版本区间读、唯一约束的数据层兜底。全部断言经 {@link StepVerifier} 对
 * Mono／Flux 信号序列进行。
 *
 * <p>用例间隔离：每用例前清空表；{@code position} 为 IDENTITY 自增不重置，凡涉
 * position 的断言只做单调性与相对顺序，不做绝对值断言。
 *
 * @author <a href="https://github.com/partme-ai">PartMe.AI</a>
 * @since 2.0.x
 */
@DisplayName("R2dbcEventStore 纯 r2dbc-h2 + H2 全量契约 IT")
class R2dbcEventStoreIT {

    private static final String AGGREGATE_TYPE = "SampleAggregate";

    /**
     * 与 -jpa/-jdbi 模块同构的 DDL（列集 parity：含 {@code tenant_id} 列、
     * {@code uk_aggregate_version} 唯一约束、TIMESTAMP WITH TIME ZONE 时间列）。
     */
    private static final String DDL = """
            create table if not exists ddd4j_stored_event (
                position bigint generated by default as identity primary key,
                event_id varchar(36) not null,
                aggregate_type varchar(128) not null,
                aggregate_id varchar(128) not null,
                version bigint not null,
                event_type varchar(256) not null,
                payload clob not null,
                correlation_id varchar(36),
                causation_id varchar(36),
                tenant_id varchar(64),
                created_at timestamp with time zone not null,
                constraint uk_aggregate_version unique (aggregate_type, aggregate_id, version)
            )""";

    private static ConnectionFactory connectionFactory;

    private static R2dbcEventStore eventStore;

    @BeforeAll
    static void setUpStore() {
        connectionFactory = ConnectionFactories.get("r2dbc:h2:mem:///esit;DB_CLOSE_DELAY=-1");
        StepVerifier.create(executeUpdate(DDL, statement -> statement)).verifyComplete();
        eventStore = new R2dbcEventStore(connectionFactory,
                new EventPayloadSerializer(JsonMapper.builder().findAndAddModules().build()));
    }

    @BeforeEach
    void cleanStream() {
        StepVerifier.create(executeUpdate("delete from ddd4j_stored_event", statement -> statement))
                .verifyComplete();
    }

    @Test
    void appendThenRead_三事件追加_应全量读回且真实Jackson往返() {
        OccurredEvent first = new OccurredEvent("created");
        OccurredEvent second = new OccurredEvent("renamed");
        OccurredEvent third = new OccurredEvent("removed");
        ItAggregateId aggregateId = new ItAggregateId("agg-1");

        StepVerifier.create(eventStore.append(AGGREGATE_TYPE, aggregateId,
                        Flux.fromIterable(List.of(first, second, third)), 0L))
                .verifyComplete();

        StepVerifier.create(eventStore.read(AGGREGATE_TYPE, aggregateId))
                .recordWith(ArrayList::new)
                .expectNextCount(3)
                .consumeRecordedWith(stored -> {
                    assertThat(stored).extracting(StoredEvent::version).containsExactly(1L, 2L, 3L);
                    // eventId／聚合定位经持久化往返保持
                    assertThat(stored).extracting(event -> event.eventId().asString())
                            .containsExactly(first.getEventId().asString(), second.getEventId().asString(),
                                    third.getEventId().asString());
                    assertThat(stored).extracting(StoredEvent::aggregateType).containsOnly(AGGREGATE_TYPE);
                    assertThat(stored).allSatisfy(event -> {
                        assertThat(event.aggregateId().asString()).isEqualTo("agg-1");
                        // 真实 Jackson 往返：payload 反序列化为原事件类型且业务字段等值
                        assertThat(event.payload()).isInstanceOf(OccurredEvent.class);
                        assertThat(event.timestamp()).isNotNull();
                        assertThat(event.position()).isPositive();
                        // 无因果事件的 correlationId/causationId 为 null（EventId.valueOf 空安全路径）
                        assertThat(event.correlationId()).isNull();
                        assertThat(event.causationId()).isNull();
                    });
                    // created_at 为 timestamp with time zone 列，r2dbc-h2 实证回读 OffsetDateTime→ZonedDateTime
                    List<StoredEvent> ordered = stored.stream().toList();
                    assertThat(((OccurredEvent) ordered.get(0).payload()).getFact()).isEqualTo("created");
                    assertThat(((OccurredEvent) ordered.get(1).payload()).getFact()).isEqualTo("renamed");
                    assertThat(((OccurredEvent) ordered.get(2).payload()).getFact()).isEqualTo("removed");
                })
                .verifyComplete();
    }

    @Test
    void append_乐观锁冲突_应错误信号且库中事件数不变() {
        ItAggregateId aggregateId = new ItAggregateId("agg-1");
        StepVerifier.create(eventStore.append(AGGREGATE_TYPE, aggregateId,
                        Flux.fromIterable(List.of(new OccurredEvent("created"), new OccurredEvent("renamed"))), 0L))
                .verifyComplete();

        StepVerifier.create(eventStore.append(AGGREGATE_TYPE, aggregateId,
                        Flux.just(new OccurredEvent("removed")), 0L))
                .verifyErrorSatisfies(error -> {
                    assertThat(error).isInstanceOf(AggregateVersionConflictException.class);
                    AggregateVersionConflictException conflict = (AggregateVersionConflictException) error;
                    assertThat(conflict.aggregateType()).isEqualTo(AGGREGATE_TYPE);
                    assertThat(conflict.aggregateId()).isEqualTo("agg-1");
                    assertThat(conflict.expectedVersion()).isZero();
                    assertThat(conflict.actualVersion()).isEqualTo(2L);
                });

        // 冲突短路且响应式事务回滚：库中仍只有已提交的 2 条，未留半截流
        StepVerifier.create(eventStore.read(AGGREGATE_TYPE, aggregateId))
                .expectNextCount(2)
                .verifyComplete();
    }

    @Test
    void readAll_跨聚合追加_应按全局position递增且SQL_limit真分页() {
        ItAggregateId firstAggregate = new ItAggregateId("agg-a");
        ItAggregateId secondAggregate = new ItAggregateId("agg-b");
        StepVerifier.create(eventStore.append(AGGREGATE_TYPE, firstAggregate,
                        Flux.fromIterable(List.of(new OccurredEvent("a1"), new OccurredEvent("a2"))), 0L))
                .verifyComplete();
        StepVerifier.create(eventStore.append(AGGREGATE_TYPE, secondAggregate,
                        Flux.fromIterable(List.of(new OccurredEvent("b1"), new OccurredEvent("b2"))), 0L))
                .verifyComplete();

        List<StoredEvent> all = eventStore.readAll(0L, 10).collectList().block();
        assertThat(all).hasSize(4);
        // 追加顺序即全局流顺序：跨聚合按 position 递增（含端点、无重复）
        assertThat(all).extracting(StoredEvent::position).isSorted().doesNotHaveDuplicates();
        assertThat(all).extracting(event -> event.aggregateId().asString())
                .containsExactly("agg-a", "agg-a", "agg-b", "agg-b");

        // SQL limit 真分页：limit=2 只取全局流前 2 条（StoredEvent 无 equals，按 position 比对）
        StepVerifier.create(eventStore.readAll(0L, 2))
                .recordWith(ArrayList::new)
                .expectNextCount(2)
                .consumeRecordedWith(page -> assertThat(page).extracting(StoredEvent::position)
                        .containsExactly(all.get(0).position(), all.get(1).position()))
                .verifyComplete();

        // fromPosition 含端点：从首条 position 起读为全量，越过后为尾部 3 条
        long firstPosition = all.get(0).position();
        StepVerifier.create(eventStore.readAll(firstPosition, 10)).expectNextCount(4).verifyComplete();
        StepVerifier.create(eventStore.readAll(firstPosition + 1, 10))
                .recordWith(ArrayList::new)
                .expectNextCount(3)
                .consumeRecordedWith(tail -> assertThat(tail).extracting(StoredEvent::position)
                        .containsExactly(all.get(1).position(), all.get(2).position(), all.get(3).position()))
                .verifyComplete();
    }

    @Test
    void readByVersionRange_应返回闭区间内事件() {
        ItAggregateId aggregateId = new ItAggregateId("agg-1");
        StepVerifier.create(eventStore.append(AGGREGATE_TYPE, aggregateId,
                        Flux.fromIterable(List.of(new OccurredEvent("v1"), new OccurredEvent("v2"),
                                new OccurredEvent("v3"))), 0L))
                .verifyComplete();

        StepVerifier.create(eventStore.read(AGGREGATE_TYPE, aggregateId, 2L, 3L))
                .recordWith(ArrayList::new)
                .expectNextCount(2)
                .consumeRecordedWith(stored ->
                        assertThat(stored).extracting(StoredEvent::version).containsExactly(2L, 3L))
                .verifyComplete();
        StepVerifier.create(eventStore.read(AGGREGATE_TYPE, aggregateId, 1L, 1L))
                .recordWith(ArrayList::new)
                .expectNextCount(1)
                .consumeRecordedWith(stored ->
                        assertThat(stored).extracting(StoredEvent::version).containsExactly(1L))
                .verifyComplete();
        // 空区间（from > to / 流不存在）返回空流，不报错
        StepVerifier.create(eventStore.read(AGGREGATE_TYPE, aggregateId, 4L, 9L)).verifyComplete();
        StepVerifier.create(eventStore.read(AGGREGATE_TYPE, new ItAggregateId("agg-none"))).verifyComplete();
    }

    /**
     * 数据层双保险：绕过 {@link R2dbcEventStore} 的语义层乐观锁，同一表内直接插入
     * 两条同 {@code (aggregate_type, aggregate_id, version)} 行——
     * {@code uk_aggregate_version} 唯一约束应让第二条插入以错误信号失败
     * （ADR-0005 第二道防线）。
     */
    @Test
    void uk_aggregate_version约束_同流重复版本直插_应违反唯一约束() {
        String insert = "insert into ddd4j_stored_event (event_id, aggregate_type, aggregate_id, version, "
                + "event_type, payload, created_at) values ($1, $2, $3, $4, $5, $6, $7)";
        UnaryOperator<Statement> firstRow = statement -> statement
                .bind(0, "11111111-1111-1111-1111-111111111111")
                .bind(1, AGGREGATE_TYPE)
                .bind(2, "agg-1")
                .bind(3, 1L)
                .bind(4, OccurredEvent.class.getName())
                .bind(5, "{}")
                .bind(6, OffsetDateTime.now());
        StepVerifier.create(executeUpdate(insert, firstRow)).verifyComplete();

        UnaryOperator<Statement> duplicateRow = statement -> statement
                .bind(0, "33333333-3333-3333-3333-333333333333")
                .bind(1, AGGREGATE_TYPE)
                .bind(2, "agg-1")
                .bind(3, 1L)
                .bind(4, OccurredEvent.class.getName())
                .bind(5, "{}")
                .bind(6, OffsetDateTime.now());
        StepVerifier.create(executeUpdate(insert, duplicateRow))
                .verifyError(R2dbcException.class);

        // 仅第一行落库（parity：tenant_id 列存在且默认为 NULL）
        StepVerifier.create(eventStore.readAll(0L, 10)).expectNextCount(1).verifyComplete();
    }

    /**
     * 直连执行 DML（建表／清表／uk 用例绕过语义层的原始插入）：连接以
     * {@code Mono.usingWhen} 托管，完成信号即成功。
     *
     * @param sql    DML 语句（占位符 {@code $n}）
     * @param binder 占位符绑参
     * @return 完成信号
     */
    private static Mono<Void> executeUpdate(String sql, UnaryOperator<Statement> binder) {
        return Mono.usingWhen(
                connectionFactory.create(),
                connection -> Mono.from(binder.apply(connection.createStatement(sql)).execute())
                        .flatMap(result -> Mono.from(result.getRowsUpdated()))
                        .then(),
                connection -> Mono.from(connection.close()),
                (connection, ex) -> Mono.from(connection.close()),
                connection -> Mono.from(connection.close()));
    }

    /**
     * IT 样本事件：带一个业务字段的 payload 载体，验证真实 Jackson 往返等值。
     */
    static final class OccurredEvent extends DomainEvent<StringEntityId> {

        private String fact;

        OccurredEvent() {
            super("agg-1");
        }

        OccurredEvent(String fact) {
            this();
            this.fact = fact;
        }

        public String getFact() {
            return fact;
        }

        public void setFact(String fact) {
            this.fact = fact;
        }
    }

    /**
     * IT 自有字符串聚合根标识（受测类内部 StringAggregateRootId 为 private，无法引用；
     * 契约与 AggregateRootId 三方法一致）。
     */
    private record ItAggregateId(String value) implements AggregateRootId {

        private static final EntityType TYPE = new StringEntityType("SampleAggregate");

        @Override
        public EntityType getType() {
            return TYPE;
        }

        @Override
        public String asString() {
            return value;
        }

        @Override
        public String asTypedString() {
            return TYPE.asString() + ":" + value;
        }
    }
}
